@echo off
setlocal enabledelayedexpansion
call "%~dp0_env.bat" || exit /b 1
cd /d "%ROOT%"

if not defined FXSTACK_CANDIDATE_BRIDGE_PORT set "FXSTACK_CANDIDATE_BRIDGE_PORT=58711"
if not defined FXSTACK_CANDIDATE_INSTANCE_ID set "FXSTACK_CANDIDATE_INSTANCE_ID=candidate"
set "FXSTACK_INSTANCE_INPUT=%FXSTACK_CANDIDATE_INSTANCE_ID%"
set "NORMALIZED_CANDIDATE_INSTANCE="
for /f "usebackq delims=" %%I in (`powershell -NoProfile -Command "$value=([string]$env:FXSTACK_INSTANCE_INPUT).Trim(); if($value -match '^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$'){ $value.ToLowerInvariant() }"`) do set "NORMALIZED_CANDIDATE_INSTANCE=%%I"
set "FXSTACK_INSTANCE_INPUT="
if not defined NORMALIZED_CANDIDATE_INSTANCE (
  echo [candidate] ERROR: FXSTACK_CANDIDATE_INSTANCE_ID must match ^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$.
  exit /b 2
)
set "FXSTACK_CANDIDATE_INSTANCE_ID=%NORMALIZED_CANDIDATE_INSTANCE%"
set "FXSTACK_INSTANCE_ID=%FXSTACK_CANDIDATE_INSTANCE_ID%"
set "RESOLVED_CANDIDATE_PORT="
for /f "usebackq delims=" %%P in (`powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0resolve_stack_endpoints.ps1" -BridgePort %FXSTACK_CANDIDATE_BRIDGE_PORT% -BridgeOnly`) do set "RESOLVED_CANDIDATE_PORT=%%P"
if not defined RESOLVED_CANDIDATE_PORT (
  echo [candidate] ERROR: no bindable candidate bridge port found.
  exit /b 2
)
if not "%RESOLVED_CANDIDATE_PORT%"=="%FXSTACK_CANDIDATE_BRIDGE_PORT%" echo [candidate] preferred port %FXSTACK_CANDIDATE_BRIDGE_PORT% unavailable; selected %RESOLVED_CANDIDATE_PORT%
set "FXSTACK_CANDIDATE_BRIDGE_PORT=%RESOLVED_CANDIDATE_PORT%"
if not exist "%ROOT%\logs" mkdir "%ROOT%\logs" >nul 2>&1
> "%ROOT%\logs\active_candidate_env.bat" echo REM Generated by 24_start_candidate_stack.bat; safe to delete while the stack is stopped.
>> "%ROOT%\logs\active_candidate_env.bat" echo set "FXSTACK_CANDIDATE_BRIDGE_PORT=%FXSTACK_CANDIDATE_BRIDGE_PORT%"
>> "%ROOT%\logs\active_candidate_env.bat" echo set "FXSTACK_CANDIDATE_INSTANCE_ID=%FXSTACK_CANDIDATE_INSTANCE_ID%"
if not defined FXSTACK_CANDIDATE_EQUITY set "FXSTACK_CANDIDATE_EQUITY=10000"
if defined FXSTACK_CANDIDATE_DATABASE_URL set "FXSTACK_DATABASE_URL=%FXSTACK_CANDIDATE_DATABASE_URL%"

echo [candidate] db migrate/verify...
call "%~dp004_db_migrate.bat"
if errorlevel 1 (
  echo [candidate] ERROR: db migrate/verify failed.
  exit /b 2
)

echo [candidate] starting bridge on :%FXSTACK_CANDIDATE_BRIDGE_PORT%
call "%~dp020_start_bridge.bat" --background %FXSTACK_CANDIDATE_BRIDGE_PORT%
if errorlevel 1 (
  echo [candidate] ERROR: bridge startup failed.
  exit /b 2
)

echo [candidate] starting runtime on :%FXSTACK_CANDIDATE_BRIDGE_PORT%
call "%~dp021_start_runtime.bat" --background %FXSTACK_CANDIDATE_EQUITY% %FXSTACK_CANDIDATE_BRIDGE_PORT% %FXSTACK_CANDIDATE_INSTANCE_ID%
if errorlevel 1 (
  echo [candidate] ERROR: runtime startup failed.
  exit /b 2
)

echo [candidate] OK
endlocal & set "FXSTACK_CANDIDATE_BRIDGE_PORT=%FXSTACK_CANDIDATE_BRIDGE_PORT%" & set "FXSTACK_CANDIDATE_INSTANCE_ID=%FXSTACK_CANDIDATE_INSTANCE_ID%"
exit /b 0
