# AGENT: ROLE: Select bindable loopback ports once and persist them for every stack consumer.
# AGENT: ENTRYPOINT: called by `launch_all.bat` before bridge/runtime/dashboard startup.
# AGENT: STATE / SIDE EFFECTS: briefly binds candidate loopback sockets and writes an ignored state file.
param(
  [ValidateRange(1, 65535)]
  [int]$BridgePort = 58710,
  [ValidateRange(1, 65535)]
  [int]$DashboardPort = 3000,
  [ValidateRange(0, 2000)]
  [int]$SearchSpan = 200,
  [string]$StateFile = "",
  [switch]$StrictBridge,
  [switch]$StrictDashboard,
  [switch]$BridgeOnly
)

$ErrorActionPreference = "Stop"
trap {
  [Console]::Error.WriteLine("[endpoints] ERROR: " + $_.Exception.Message)
  exit 2
}

function Test-LoopbackPortAvailable {
  param([int]$Port)

  $listener = $null
  try {
    $listener = [System.Net.Sockets.TcpListener]::new(
      [System.Net.IPAddress]::Loopback,
      $Port
    )
    $listener.Start()
    return $true
  } catch [System.Net.Sockets.SocketException] {
    # Binding catches both active listeners and Windows excluded TCP ranges.
    return $false
  } finally {
    if ($null -ne $listener) {
      try { $listener.Stop() } catch {}
    }
  }
}

function Resolve-Port {
  param(
    [int]$Preferred,
    [bool]$Strict,
    [int[]]$Reserved = @()
  )

  $limit = if ($Strict) { 0 } else { $SearchSpan }
  foreach ($offset in 0..$limit) {
    $candidate = $Preferred + $offset
    if ($candidate -gt 65535) { break }
    if ($Reserved -contains $candidate) { continue }
    if (Test-LoopbackPortAvailable -Port $candidate) { return $candidate }
  }
  $mode = if ($Strict) { "requested" } else { "preferred/search range" }
  throw "No bindable loopback port found for $mode starting at $Preferred"
}

$resolvedBridge = Resolve-Port -Preferred $BridgePort -Strict ([bool]$StrictBridge)
$resolvedDashboard = $null
if (-not $BridgeOnly) {
  $resolvedDashboard = Resolve-Port -Preferred $DashboardPort -Strict ([bool]$StrictDashboard) -Reserved @($resolvedBridge)
}

if ($StateFile) {
  $statePath = [System.IO.Path]::GetFullPath($StateFile)
  $stateParent = Split-Path -Parent $statePath
  if ($stateParent) { New-Item -ItemType Directory -Path $stateParent -Force | Out-Null }
  $lines = @(
    "REM Generated by resolve_stack_endpoints.ps1; safe to delete while the stack is stopped.",
    "set `"TRADER_BRIDGE_HOST=127.0.0.1`"",
    "set `"TRADER_BRIDGE_PORT=$resolvedBridge`""
  )
  if (-not $BridgeOnly) {
    $lines += "set `"TRADER_DASHBOARD_HOST=127.0.0.1`""
    $lines += "set `"TRADER_DASHBOARD_PORT=$resolvedDashboard`""
  }
  [System.IO.File]::WriteAllLines($statePath, $lines, [System.Text.UTF8Encoding]::new($false))
}

if ($BridgeOnly) {
  Write-Output $resolvedBridge
} else {
  Write-Output ("{0}|{1}" -f $resolvedBridge, $resolvedDashboard)
}
